# Generated by Django 4.1.7 on 2023-05-15 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name="Car",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=32)),
                (
                    "style",
                    models.CharField(
                        choices=[
                            ("SD", "Sedan"),
                            ("HB", "Hatchback"),
                            ("CR", "SUV & Crossover"),
                            ("TR", "Truck & Van"),
                            ("CN", "Convertible"),
                        ],
                        default="SD",
                        max_length=2,
                    ),
                ),
                (
                    "power",
                    models.CharField(
                        choices=[
                            ("GS", "Gasoline"),
                            ("DS", "Diesel"),
                            ("EL", "Electricity"),
                            ("HY", "Hydrogen"),
                        ],
                        default="GS",
                        max_length=2,
                    ),
                ),
                ("capacity", models.FloatField(default=1.6)),
                ("passengers", models.PositiveSmallIntegerField(default=5)),
                ("doors", models.PositiveSmallIntegerField(default=4)),
                ("boot_space", models.PositiveIntegerField(default=500)),
                ("consumption", models.FloatField()),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cars",
                        to="drivex.brand",
                    ),
                ),
                (
                    "features",
                    models.ManyToManyField(related_name="cars", to="drivex.feature"),
                ),
            ],
        ),
    ]
