# Generated by Django 4.1.7 on 2023-05-15 15:47

from django.db import migrations, models
import drivex.functions


class Migration(migrations.Migration):
    dependencies = [
        ("drivex", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="car",
            old_name="model",
            new_name="name",
        ),
        migrations.AddField(
            model_name="brand",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=drivex.functions.UploadToPathAndRename("brands"),
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=drivex.functions.UploadToPathAndRename("cars"),
            ),
        ),
        migrations.AddField(
            model_name="car",
            name="rating",
            field=models.FloatField(default=5.0),
        ),
    ]
