# Generated by Django 4.1.7 on 2023-05-15 16:26

from django.db import migrations, models
import drivex.functions


class Migration(migrations.Migration):
    dependencies = [
        ("drivex", "0003_alter_car_features"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="features",
            field=models.ManyToManyField(
                blank=True, related_name="cars", to="drivex.feature"
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="image",
            field=models.ImageField(
                default="settings.MEDIA_ROOT/cars/car.png",
                upload_to=drivex.functions.UploadToPathAndRename("cars"),
            ),
        ),
    ]
