# Generated by Django 4.1.7 on 2023-05-16 13:36

from django.db import migrations, models
import drivex.functions


class Migration(migrations.Migration):
    dependencies = [
        ("drivex", "0004_alter_car_features_alter_car_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="image",
            field=models.ImageField(
                blank=True,
                default="settings.MEDIA_ROOT/cars/car.png",
                upload_to=drivex.functions.UploadToPathAndRename("cars"),
            ),
        ),
    ]
