# Generated by Django 4.1.7 on 2023-05-16 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("drivex", "0005_alter_car_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brand",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="brands"),
        ),
        migrations.AlterField(
            model_name="car",
            name="image",
            field=models.ImageField(
                blank=True, default="settings.MEDIA_ROOT/cars/car.png", upload_to="cars"
            ),
        ),
    ]
