# Generated by Django 4.1.7 on 2023-05-18 07:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("drivex", "0007_alter_car_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="transmission",
            field=models.CharField(
                choices=[
                    ("AT", "Automatic Transmission"),
                    ("MT", "Manual Transmission"),
                ],
                default="MT",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="power",
            field=models.CharField(
                choices=[
                    ("GS", "Gasoline"),
                    ("DS", "Diesel"),
                    ("EL", "Electricity"),
                    ("HY", "Hybrid"),
                ],
                default="GS",
                max_length=2,
            ),
        ),
    ]
