# Generated by Django 4.1.7 on 2023-05-18 10:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("drivex", "0009_badge_car_badges"),
    ]

    operations = [
        migrations.RenameField(
            model_name="car",
            old_name="badges",
            new_name="badge",
        ),
    ]
