# Generated by Django 4.1.7 on 2023-05-18 11:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("drivex", "0010_rename_badges_car_badge"),
    ]

    operations = [
        migrations.AddField(
            model_name="badge",
            name="color",
            field=models.CharField(
                choices=[
                    ("#7400C8", "violet"),
                    ("#ff8e30", "orange"),
                    ("#70d628", "green"),
                    ("#12bbee", "blue"),
                ],
                default="#7400C8",
                max_length=7,
            ),
        ),
    ]
