# Generated by Django 4.1.7 on 2023-05-19 16:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("drivex", "0011_badge_color"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name="car",
            name="price",
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name="badge",
            name="color",
            field=models.CharField(
                choices=[
                    ("#7400C8", "violet"),
                    ("#ff8e30", "orange"),
                    ("#70d628", "green"),
                    ("#12bbee", "blue"),
                    ("#cc614b", "red"),
                ],
                default="#7400C8",
                max_length=7,
            ),
        ),
        migrations.AlterField(
            model_name="car",
            name="transmission",
            field=models.CharField(
                choices=[("AT", "Automatic"), ("MT", "Manual")],
                default="MT",
                max_length=2,
            ),
        ),
    ]
