# Generated by Django 4.1.7 on 2023-05-19 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("drivex", "0012_category_car_price_alter_badge_color_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="cars",
                to="drivex.category",
            ),
        ),
    ]
