# Generated by Django 4.1.7 on 2023-05-19 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("drivex", "0013_car_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="category",
            field=models.ForeignKey(
                default="Standart",
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="cars",
                to="drivex.category",
                to_field="name",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
