# Generated by Django 4.1.7 on 2023-05-19 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("drivex", "0014_alter_car_category_alter_category_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cars",
                to="drivex.category",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=32),
        ),
    ]
