# Generated by Django 4.1.7 on 2023-05-19 17:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("drivex", "0015_alter_car_category_alter_category_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="badge",
            name="color",
            field=models.CharField(
                choices=[
                    ("#7400C8", "violet"),
                    ("#ff8e30", "orange"),
                    ("#70d628", "green"),
                    ("#12bbee", "blue"),
                    ("#EA0D01", "red"),
                ],
                default="#7400C8",
                max_length=7,
            ),
        ),
    ]
