# Generated by Django 4.1.7 on 2023-05-22 15:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("drivex", "0017_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="photo",
            field=models.ImageField(
                blank=True, default="/static/drivex/img/user.jpg", upload_to="users"
            ),
        ),
    ]
