# Generated by Django 4.1.7 on 2023-05-22 16:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("drivex", "0018_alter_profile_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="photo",
            field=models.ImageField(blank=True, upload_to="users"),
        ),
    ]
