# Generated by Django 4.1.7 on 2023-05-23 17:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("drivex", "0021_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="date_start",
            field=models.DateField(
                default=datetime.datetime(2023, 5, 23, 20, 2, 21, 435672)
            ),
        ),
    ]
