# Generated by Django 4.1.7 on 2023-05-24 06:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("drivex", "0022_alter_order_date_start"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="date_start",
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
