# Generated by Django 4.1.7 on 2023-05-24 12:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("drivex", "0023_alter_order_date_start"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="consumption",
            field=models.FloatField(default=8.0),
        ),
    ]
