# Generated by Django 4.1.7 on 2023-05-25 15:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("drivex", "0028_car_avg_rating"),
    ]

    operations = [
        migrations.RenameField(
            model_name="carrating",
            old_name="value",
            new_name="stars",
        ),
    ]
