# Generated by Django 4.1.7 on 2023-05-26 07:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("drivex", "0029_rename_value_carrating_stars"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
