# Generated by Django 4.1.7 on 2023-05-26 12:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("drivex", "0030_order_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="favorites",
            field=models.ManyToManyField(
                blank=True, related_name="favorites", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
