# Generated by Django 4.1.7 on 2023-05-26 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("drivex", "0031_car_favorites"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="car",
            name="features",
        ),
        migrations.AddField(
            model_name="car",
            name="features",
            field=models.ForeignKey(
                blank=True,
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cars",
                to="drivex.feature",
            ),
        ),
    ]
