# Generated by Django 4.1.7 on 2023-05-26 14:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("drivex", "0032_remove_car_features_car_features"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="car",
            name="features",
        ),
        migrations.AddField(
            model_name="car",
            name="features",
            field=models.ManyToManyField(
                blank=True, related_name="cars", to="drivex.feature"
            ),
        ),
    ]
