# Generated by Django 4.1.7 on 2023-05-28 10:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("drivex", "0034_review_delete_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="car",
            name="rating",
        ),
        migrations.AlterField(
            model_name="car",
            name="avg_rating",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="rate",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="CarRating",
        ),
    ]
